development:
  mandrill_user_name: <%= ENV["MANDRILL_USER_NAME"] %>
  mandrill_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  default_from_address: <%= ENV["DEFAULT_FROM_ADDRESS"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>  
  host_url: <%= ENV["HOST_URL"] %>
  youtube_stream_length: <%= ENV["YOUTUBE_STREAM_LENGTH"] %>

production:
  mandrill_user_name: <%= ENV["MANDRILL_USER_NAME"] %>
  mandrill_api_key: <%= ENV["MANDRILL_API_KEY"] %>
  default_from_address: <%= ENV["DEFAULT_FROM_ADDRESS"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  host_url: <%= ENV["HOST_URL"] %>
  youtube_stream_length: <%= ENV["YOUTUBE_STREAM_LENGTH"] %>


